"""Post-hoc decoded rollout galleries and metadata."""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F
from numpy.typing import NDArray
from torch import Tensor

from lewm_liquid_predictors.data import IMAGENET_MEAN, IMAGENET_STD, ObservationTrajectory

from .model import CrossAttentionDecoder


def write_decoded_galleries(
    output_dir: str | Path,
    queries: Sequence[tuple[ObservationTrajectory, Tensor]],
    decoder: CrossAttentionDecoder,
    horizons: Sequence[int],
    decoder_checkpoint: str | Path | None = None,
) -> None:
    """Write labeled post-hoc decoded rollout PNGs and ``decoded.json`` metadata."""
    import imageio.v3 as imageio

    directory = Path(output_dir)
    if not directory.exists():
        raise FileNotFoundError(f"output directory does not exist: {directory}")
    if not directory.is_dir():
        raise NotADirectoryError(directory)
    configured_horizons = tuple(horizons)
    if any(isinstance(horizon, bool) or horizon <= 0 for horizon in configured_horizons):
        raise ValueError("horizons must be positive integers")

    decoder_device = _decoder_device(decoder)
    image_size = decoder.architecture.image_size
    records: list[dict[str, object]] = []
    was_training = decoder.training
    decoder.eval()
    try:
        with torch.no_grad():
            for query_index, (trajectory, rollout) in enumerate(queries):
                input_frame = _source_image(trajectory.observations[0], image_size)
                rows: list[tuple[int, NDArray[np.uint8], NDArray[np.uint8]]] = []
                for horizon in configured_horizons:
                    if horizon > rollout.shape[0] or horizon >= trajectory.observations.shape[0]:
                        continue
                    prediction = decoder(rollout[horizon - 1].unsqueeze(0).to(decoder_device))[0]
                    decoded = _decoded_image(prediction)
                    actual = _source_image(trajectory.observations[horizon], image_size)
                    rows.append((horizon, decoded, actual))
                    records.append(
                        {
                            "query_index": query_index,
                            "query_episode_id": trajectory.episode_id,
                            "input_timestep": 0,
                            "horizon": horizon,
                            "actual_timestep": horizon,
                        }
                    )
                if rows:
                    imageio.imwrite(
                        directory / f"decoded_{trajectory.episode_id}.png",
                        build_decoded_gallery(input_frame, rows),
                    )
    finally:
        decoder.train(was_training)

    metadata: dict[str, object] = {
        "description": "Images generated by a post-hoc decoder from predicted LeWM latent "
        "rollouts; they are decoder reconstructions, not direct dynamics-model pixels.",
        "generated_by": "post-hoc decoder",
        "gallery_columns": ["Initial input", "Decoded prediction", "Actual future"],
        "records": records,
    }
    if decoder_checkpoint is not None:
        metadata["decoder_checkpoint"] = str(decoder_checkpoint)
    (directory / "decoded.json").write_text(
        json.dumps(metadata, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )


def build_decoded_gallery(
    input_frame: NDArray[np.uint8],
    rows: Sequence[tuple[int, NDArray[np.uint8], NDArray[np.uint8]]],
) -> NDArray[np.uint8]:
    """Build one labeled three-column decoded rollout gallery."""
    import cv2

    if not rows:
        raise ValueError("decoded gallery requires at least one row")
    _, width, channels = input_frame.shape
    if channels != 3:
        raise ValueError("decoded gallery images must be RGB")
    expected_shape = input_frame.shape
    if any(
        image.shape != expected_shape
        for _, predicted, actual in rows
        for image in (predicted, actual)
    ):
        raise ValueError("decoded gallery images must share a shape")

    columns = ("Initial input", "Decoded prediction", "Actual future")
    header = np.concatenate(tuple(_text_banner(width, 30, title, cv2) for title in columns), axis=1)
    gallery_rows: list[NDArray[np.uint8]] = [header]
    for horizon, prediction, actual in rows:
        gallery_rows.append(_text_banner(width * 3, 24, f"Rollout horizon: {horizon}", cv2))
        gallery_rows.append(np.concatenate((input_frame, prediction, actual), axis=1))
    return np.concatenate(gallery_rows, axis=0)


def _source_image(observation: Tensor, image_size: int) -> NDArray[np.uint8]:
    if observation.ndim != 3:
        raise ValueError("source frame must have CHW or HWC shape")
    if observation.shape[0] == 3:
        image = observation
    elif observation.shape[-1] == 3:
        image = observation.movedim(-1, 0)
    else:
        raise ValueError("source frame must be RGB")
    image = image.float() / 255.0 if image.dtype == torch.uint8 else image.float()
    resized = F.interpolate(
        image.unsqueeze(0),
        size=(image_size, image_size),
        mode="bilinear",
        align_corners=False,
    )[0]
    return _uint8_image(resized)


def _decoded_image(normalized: Tensor) -> NDArray[np.uint8]:
    mean = normalized.new_tensor(IMAGENET_MEAN).view(3, 1, 1)
    std = normalized.new_tensor(IMAGENET_STD).view(3, 1, 1)
    return _uint8_image(normalized * std + mean)


def _uint8_image(image: Tensor) -> NDArray[np.uint8]:
    pixels = (image.float().clamp(0, 1) * 255).round().to(torch.uint8)
    return np.asarray(pixels.permute(1, 2, 0).cpu(), dtype=np.uint8)


def _decoder_device(decoder: CrossAttentionDecoder) -> torch.device:
    parameter = next(decoder.parameters(), None)
    if parameter is not None:
        return parameter.device
    return torch.device("cpu")


def _text_banner(width: int, height: int, text: str, cv2: Any) -> NDArray[np.uint8]:
    banner = np.full((height, width, 3), 255, dtype=np.uint8)
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.42
    thickness = 1
    while True:
        (text_width, text_height), _ = cv2.getTextSize(text, font, font_scale, thickness)
        if text_width <= width - 6 or font_scale <= 0.2:
            break
        font_scale -= 0.02
    origin = (max(3, (width - text_width) // 2), (height + text_height) // 2)
    cv2.putText(
        banner,
        text,
        origin,
        font,
        font_scale,
        (35, 35, 35),
        thickness,
        cv2.LINE_AA,
    )
    return banner
